/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 28a7d7bd9de05567911a9522bf277b4b)
interface __BaseEnv_Env {
	DATABASE: D1Database;
	ASSETS: Fetcher;
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET">> {}
}
